### ISSUE TITLE
没有ffmpeg FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

### ISSUE THREAD

**Issue by Crescentz** [Henry-23/VideoChat#22]
并行推理模式已开启
分桶处理模式已开启
Traceback (most recent call last):
  File "/home/yons/CODE/video_chat/src/GPT_SoVITS/tools/my_utils.py", line 20, in load_audio
    ffmpeg.input(file, threads=0)
  File "/home/yons/miniconda3/envs/video_chat/lib/python3.10/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/home/yons/miniconda3/envs/video_chat/lib/python3.10/site-packages/ffmpeg/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/home/yons/miniconda3/envs/video_chat/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/yons/miniconda3/envs/video_chat/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

**Comment by Crescentz** [comment]
conda install
