### ISSUE TITLE
启动报错，这个是啥原因？

### ISSUE THREAD

**Issue by mwzzz** [Henry-23/VideoChat#26]
[2/4] Start initializing funasr
funasr version: 1.1.6.
2024-12-05 16:27:50,767 - modelscope - WARNING - Using branch: master as version is unstable, use with caution
[3/4] Start initializing qwen
Traceback (most recent call last):
  File "/mnt/workspace/video_chat/app.py", line 46, in <module>
    from src.pipeline_llm import llm_pipeline
  File "/mnt/workspace/video_chat/src/pipeline_llm.py", line 348, in <module>
    llm_pipeline = LLMPipeline()
  File "/mnt/workspace/video_chat/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/workspace/video_chat/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 129, in <lambda>
    func = cast(F, lambda *args, **kwargs: orig_func(*args, **kwargs))
  File "/mnt/workspace/video_chat/src/pipeline_llm.py", line 40, in __init__
    self.llm = Qwen_API()
  File "/mnt/workspace/video_chat/src/llm.py", line 131, in __init__
    self.client = OpenAI(
  File "/mnt/workspace/video_chat/venv/lib/python3.10/site-packages/openai/_client.py", line 123, in __init__
    super().__init__(
  File "/mnt/workspace/video_chat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 844, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/mnt/workspace/video_chat/venv/lib/python3.10/site-packages/openai/_base_client.py", line 742, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

**Comment by chien325** [comment]
downgrade httpx to 0.27.2 can fix it.
