### ISSUE TITLE
模型加载问题

### ISSUE THREAD

**Issue by Upcreat** [Henry-23/VideoChat#5]
按照项目流程进行部署，但是出现了下面模型加载问题，请问这是什么原因呀
Loads checkpoint by local backend from path: weights/dwpose/dw-ll_ucoco_384.pth
cuda start
Load from local weight: /home/pod/shared-nvme/VideoChat/video_chat/src/musetalk/utils/face_detection/detection/sfd/s3fd.pth
Traceback (most recent call last):
  File "/home/pod/shared-nvme/VideoChat/video_chat/app.py", line 45, in <module>
    from src.pipeline_llm import llm_pipeline
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/pipeline_llm.py", line 25, in <module>
    from src.thg import Muse_Talk
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/thg.py", line 25, in <module>
    from src.musetalk.utils.blending import get_image,get_image_prepare_material,get_image_blending
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/musetalk/utils/blending.py", line 6, in <module>
    fp = FaceParsing()
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/musetalk/utils/face_parsing/__init__.py", line 12, in __init__
    self.net = self.model_init()
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/musetalk/utils/face_parsing/__init__.py", line 18, in model_init
    net = BiSeNet(resnet_path)
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/musetalk/utils/face_parsing/model.py", line 233, in __init__
    self.cp = ContextPath(resnet_path)
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/musetalk/utils/face_parsing/model.py", line 95, in __init__
    self.resnet = Resnet18(resnet_path)
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/musetalk/utils/face_parsing/resnet.py", line 69, in __init__
    self.init_weight(model_path)
  File "/home/pod/shared-nvme/VideoChat/video_chat/src/musetalk/utils/face_parsing/resnet.py", line 83, in init_weight
    state_dict = torch.load(model_path) #modelzoo.load_url(resnet18_url)
  File "/home/pod/miniconda3/envs/metahuman/lib/python3.10/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/pod/miniconda3/envs/metahuman/lib/python3.10/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by Henry-23** [comment]
weights文件夹里的权重下载了吗？

**Comment by Upcreat** [comment]
重新试了一下，原因是模型没有下载完全，下载的模型不完整。

**Comment by changQiangXia** [comment]
和这哥们问题一样,关键是我检查了下载的模型,依旧报同样的错

**Comment by TuuSiwei** [comment]
同样的问题，使用hfd下载的模型明明是完整的
